import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../Components/navbar"

export default function Home() {

  return (
    <div>
      <Head>
        <title>Secure-DePART</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="Images/Bg.png" alt="" className={styles.Background} />
      <Navbar/>
      <div className={styles.container}>
      <div className={styles.headlines}>
      <h1>Decentralized Packaging and Return Technology</h1>
      <h3>Revolutionalizing the future of customer trust.</h3>
      <button>Connect Wallet</button>
      </div>
    </div>
    </div>
  );
}
