import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Secure-DePART</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.formContainer}>
     <div className={styles.form}>
      <h1>WELCOME TO SECURE DEPART</h1>
      <label className={styles.label} type="username">Username</label>
        <input className={styles.input} type="text" placeholder="Email or Phone" id="username" />

        <label className={styles.label} type="password">Password</label>
        <input className={styles.input} type="password" placeholder="Password" id="password" />

        <button className={styles.button}>Log In</button>
        <div className={styles.social}>
          <div className={styles.go}><i ></i>  Google</div>
        </div>
     </div>
     </div>
     
    </div>
  )
}
